mysite/blog/urls.py
""" the URL pattern maps urls to views , its composed of a string pattern , a view and optionally a name  """
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # <int:id> is a path converter , any value from the url is a string 
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name ='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path,include
from blog.sitemaps import PostSitemap

sitemaps = {
    'post': PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, 
         name='django.contrib.sitemaps.views.sitemap')
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings 
from django.urls import reverse
from taggit.managers import TaggableManager



# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)





class Post(models.Model):
    
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED ='PB', 'Published'
    # adding a tag object
    tags = TaggableManager()
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # one to many relationshp between the user and the posts , djanog handels this relation with pre-built authentication model
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    # to save time automatically when created 
    created = models.DateTimeField(auto_now_add=True)
    # to save time automatically when updated
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices = Status,
        default=Status.DRAFT
    )
    objects = models.Manager()
    published = PublishedManager()
    
    class Meta:
        ordering  = ['-publish']
        indexes = [
            models.Index(fields = ['-publish']),
        ]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        indexes = [models.Index(fields=['created'])]
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

    

mysite/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False, widget=forms.Textarea
        )
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']
        # the forms will take into account the field types from the models 

mysite/blog/views.py
from django.db.models import Count
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView
from django.views.decorators.http import require_POST
from django.http import Http404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # if the form is valid retrieve the cleaned data
            cd = form.cleaned_data
            
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} ({cd['email']}) recommends you read {post.title}"
            message = (f"Read {post.title} at {post_url}\n\n"
           f"{cd['name']}'s comments: {cd['comments']}")
            send_mail(
                subject=subject,
                message = message,
                from_email=None,
                recipient_list = [cd['to']],
            )
            sent = True
    else:
        form = EmailPostForm()   
    return render(request, 'blog/post/share.html', 
                  {
                      'post':post,
                      'form':form,
                      'sent':sent,
                  })     

def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    paginator = Paginator(post_list,3)
    page_number = request.GET.get('page', 1)

    try:
     posts = paginator.page(page_number)
    except PageNotAnInteger:
    # If page_number is not an integer get the first page
     posts = paginator.page(1)
    except EmptyPage:
    # If page_number is out of range get last page of results
     posts = paginator.page(paginator.num_pages)
    return render(
    request,
    'blog/post/list.html',
    {
    'posts': posts,
    'tag': tag
    }

    )


def post_detail(request, year,month,day,post):
    post = get_object_or_404(Post,slug=post, publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    # get the ids for the tags of the current post
    post_tags_ids = post.tags.values_list('id', flat=True)
    # get the posts which have the same tags excluding the current one 
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    # adding an aaditional field to the object that has the number of the tags for each post
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-publish')
    
    
    
    return render(request, 'blog/post/detail.html',
                  {'post':post,
                   'comments':comments,
                   'form':form,
                   'similar_posts': similar_posts})
    
    
    
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id = post_id,
        status = Post.Status.PUBLISHED
    )
    comment = None
    form = CommentForm(data = request.POST)
    if form.is_valid():
        # create a comment object without saving it ot the data base
        comment = form.save(commit=False)
        # assigne the comment to the post
        comment.post = post
        # save the comment to the data base
        comment.save()
        return render(
            request,
            'blog/post/comment.html',
            {
                'post':post,
                'form': form,
                'comment': comment
            }
        )

mysite/blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {%block title %}{% endblock %} </title>
    <link rel="stylesheet" href=" {% static "css/blog.css" %} ">
</head>
<body>
    <div id='content'>
        {%block content%}{%endblock%}
    </div>

    <div id="sidebar">
        <h2>my blog</h2>
        <p>this is me blog 
            I ve written {% total_posts %} so far
        </p>
        <p>
            <a href="{% url "blog:post_feed" %}">
                Subscribe To My RSS Feed
            </a>
        </p>
        <h3>Latest posts </h3>
        {% show_latest_posts 3 %}
        <h3> Most commented posts </h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href="{{ post.get_absolute_url }}">{{post.title}}  </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

mysite/blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %} Adda a comment {% endblock title %} 
{% block content %} 
{% if comment %}
<h2> your comment has been added </h2>
<p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
{% else %}
{% include 'blog/post/includes/comment_form.html' %}
{% endif %}
{% endblock content %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %} {{ post.title }} {% endblock %}

{%  block content %} 
<h1> {{ post.title }} </h1>
<p class="date">Published {{post.publish}} by {{ post.author }} </p>

{{ post.body|markdown}}

<p>
    <a href="{% url "blog:post_share" post.id %}"> Share this post </a>
</p>


<h2>Similar Posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}"> {{ post.title }} </a>
</p>
{{ empty }} There are no similar posts yet
{% endfor %}

{%  with comments.count as totatl_comments %} 
<h2>
    {{ totatl_comments  }} comment{{ totatl_comments|pluralize }}
</h2>

{% endwith %}
{% for comment in comments %}
<div class="comment">
<p class="info">
Comment {{ forloop.counter }} by {{ comment.name }}
{{ comment.created }}
</p>
{{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments.</p>
{% endfor %}
{% include "blog/post/includes/comment_form.html" %}
{% endblock %}

mysite/blog/templates/blog/post/includes/comment_form.html
<h2> Add a new comment</h2>
<!-- when the user clicks send the data is sent to the url specified with the post.id as a parameter  -->
<form action="{% url "blog:post_comment" post.id %}" method='post'>
    <!-- field_groups allow you to easly customize form rendering -->
    <div class="left">
        {{ form.name.as_field_group }}
    </div>
    <div class="left">
        {{ form.email.as_field_group }}
    </div>
    {{ form.body.as_field_group }}
    {% csrf_token %}
    <p><input type="submit" value='Add comment'></p>
</form>

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}"> {{ post.title }}  </a>
    </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %} 
{% load blog_tags %}
{% include "blog/pagination.html" with page=posts %}


{% block title%}my blog{%endblock%}

{%block content%}
<h1>My Blog</h1>
{% if tag %}
<h2>Posts tagged with "{{tag.name}}"  </h2>
{% endif %}
{% for post in posts %}
<h2>
    <a href="{{ post.get_absolute_url}}">
        {{ post.title }}
    </a>
</h2>
<p class="tags">Tags:
   {% for tag in post.tags.all   %}
    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" >
        {{tag.name}}
    </a> {% if not forloop.last %},{% endif %}
   
   {% endfor %}


</p>
<p class='date'> {{post.publish}} by {{post.author}} </p>

{{post.body|markdown|truncatewords_html:30}}

{% endfor %}
{% include "blog/pagination.html" with page=posts %}
{%endblock%}

mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %} Share a Post {% endblock %}

{% block content %}
{% if sent %}
<h1> E-mail successfully sent </h1>
<p>
    {{ post.title }} was sent successfuly sent to {{ form.cleaned_data.to }}
</p>

{% else %}
<h1> Share "{{ post.title }}" by E-mail </h1>
<form methode='post'>
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" value='Send e-mail'>
</form>

{% endif %}

{% endblock %}